# PHP
alias cu='composer update'
alias ci='composer install'
alias cda='composer dump-autoload -o'


# laravel
alias art="php artisan"
alias migrate="php artisan migrate"
alias migrate:r='php artisan migrate:refresh'
alias migrate:rs='php artisan migrate:refresh --seed'


# docker || docker-compose || k8s
alias d='docker'
alias dc='docker-compose'
alias dce='docker-compose exec'
alias k='kubectl'

# others
alias copyssh="pbcopy < $HOME/.ssh/id_rsa.pub"
alias reloadcli="source $HOME/.zshrc"
alias shrug="echo '¯\_(ツ)_/¯' | pbcopy"
alias publicip='dig +short myip.opendns.com @resolver1.opendns.com'


# functions
*** This one opens a PR from the current branch
function openpr() {
  br=`git branch | grep "*"`
  repo=$1
  parentBranch=$2

  open -a /Applications/Google\ Chrome.app  https://github.com/${repo/* /}/compare/${parentBranch/* /}...themsaid:${br/* /}\?expand\=1
}

# laravel functions
artisan() {
  if [ -f bin/artisan ]; then
    php bin/artisan "$@"
  else
    php artisan "$@"
  fi
}

t() {
  if [ -f vendor/bin/phpunit ]; then
    vendor/bin/phpunit "$@"
  else
    phpunit "$@"
  fi
}